# Generated by Django 5.2.7 on 2025-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_previews/'),
        ),
    ]
